# Generated by Django 3.0.5 on 2020-04-07 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Imię')),
                ('second_name', models.CharField(max_length=255, verbose_name='Nazwisko')),
                ('postal_code', models.CharField(max_length=6, verbose_name='Kod pocztowy')),
                ('street', models.CharField(max_length=255, verbose_name='Ulica')),
                ('city', models.CharField(max_length=255, verbose_name='Miasto')),
                ('nip', models.PositiveIntegerField(verbose_name='NIP')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255, verbose_name='Produkt')),
                ('price', models.PositiveIntegerField(verbose_name='Cena netto')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=10000)),
                ('begin_date', models.DateField()),
                ('finish_date', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dayoff.Client', verbose_name='Klient')),
            ],
        ),
    ]
