# Generated by Django 3.0.5 on 2020-06-04 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dayoff', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='second_name',
            new_name='last_name',
        ),
    ]
